name: Playstore deployment
on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
   build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v2.5.0
        with:
          java-version: 16.x
      - uses: subosito/flutter-action@v1.5.3
        with:
          flutter-version: 2.8.1
      - run: flutter pub get
      - run: flutter build appbundle
